"""initial_migration

Revision ID: 2c93c620104c
Revises: fff579103cc5
Create Date: 2026-06-15 20:20:16.789905

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2c93c620104c'
down_revision: Union[str, Sequence[str], None] = 'fff579103cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingrediente', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('pago', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('pago', 'transaction_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pago', 'mp_preference_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=True)
    op.alter_column('pago', 'mp_init_point',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
    op.alter_column('pedido', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pedido', 'descuento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pedido', 'costo_envio',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pedido', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('producto_ingrediente', 'unidad_medida_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto_ingrediente', 'unidad_medida_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedido', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('pedido', 'costo_envio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('pedido', 'descuento',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('pedido', 'subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('pago', 'mp_init_point',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('pago', 'mp_preference_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('pago', 'transaction_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('pago', 'deleted_at')
    op.drop_column('ingrediente', 'deleted_at')
    # ### end Alembic commands ###
